openapi: 3.0.0
info:
  title: product-service-API
  version: 1.0.0
  description: API pour les produits

paths:
  /products:
    get:
      summary: Récupérer la liste des produits
      operationId: getProducts
      responses:
        '200':
          description: Liste des produits récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/Product.yml'

  /products/{productId}:
    get:
      summary: Récupérer un produit par ID
      operationId: getProduct
      parameters:
        - name: productId
          in: path
          required: true
          description: ID du produit
          schema:
            type: integer
      responses:
        '200':
          description: Produit récupéré avec succès
          content:
            application/json:
              schema:
                $ref: './model/Product.yml'